// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"916","screenHeight":"724","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"TitleCommandPosition","status":true,"description":"Changes the position of the title command window.","parameters":{"Offset X":"-188","Offset Y":"95","Width":"540","Background":"0"}},
{"name":"ATB_WIP","status":true,"description":"ATB.","parameters":{"base":"300.00000","divider":"15.00000","atb_x":"Graphics.boxWidth - this.width","hud_x":"500","hud_y":"400"}}
];
